from feast import Entity, FeatureView, Field, FileSource, PushSource, ValueType
from feast.types import Float32, Int64, Bool
from datetime import timedelta

# ------------------------------------------------------------------
# 1. ENTITY DEFINITION
# ------------------------------------------------------------------
# This represents the primary key for the features.
machine = Entity(
    name="machine_id", 
    join_keys=["machine_id"],
    value_type=ValueType.STRING,
    description="Unique ID of the industrial laundry machine"
)

# ------------------------------------------------------------------
# 2. DATA SOURCE DEFINITION
# ------------------------------------------------------------------
# This points to the Parquet file generated by feature_engineering.py
# ensuring the offline store uses the exact same data as the research.
historical_source = FileSource(
    path="../data/features/final_features.parquet",
    event_timestamp_column="timestamp"
)

# This is the "Speed Lane" for real-time Kafka data
online_push_source = PushSource(
    name="telemetry_push_source",
    batch_source=historical_source
)

# ------------------------------------------------------------------
# 3. FEATURE VIEW DEFINITION
# ------------------------------------------------------------------
# This registers all engineering logic into the store.
machine_health_view = FeatureView(
    name="machine_health_features",
    entities=[machine],
    ttl=timedelta(days=7), # In production, features older than 7 days are considered 'stale'
    schema=[
        # --- 1. ENGINEERED ROLLING FEATURES (7-DAY) ---
        Field(name="vibration_rolling_mean_7d", dtype=Float32),
        Field(name="vibration_rolling_max_7d", dtype=Float32),
        Field(name="temp_rolling_std_7d", dtype=Float32),
        Field(name="pressure_rolling_mean_7d", dtype=Float32),
        Field(name="power_rolling_max_7d", dtype=Float32),

        # --- 2. ENGINEERED TIME & METADATA ---
        Field(name="hours_since_maintenance", dtype=Float32),
        Field(name="age_months", dtype=Int64),

        # --- 3. RAW SENSORS & COUNTERS ---
        # If the model uses the 'current' values alongside the 'rolling' ones, 
        # they must be defined here.
        Field(name="temperature_c", dtype=Float32),
        Field(name="vibration_hz", dtype=Float32),
        Field(name="pressure_bar", dtype=Float32),
        Field(name="power_kw", dtype=Float32),
        Field(name="runtime_hours", dtype=Float32),
        Field(name="error_code_count", dtype=Int64),

        # --- 4. ONE-HOT ENCODED LOCATIONS ---
        # Generated from: pd.get_dummies(..., prefix='loc')
        # Assuming locations are A, B, C, D based on previous outputs
        Field(name="loc_Warehouse A", dtype=Bool),
        Field(name="loc_Warehouse B", dtype=Bool),
        Field(name="loc_Warehouse C", dtype=Bool),
        Field(name="loc_Warehouse D", dtype=Bool),

        # --- 5. ONE-HOT ENCODED AGE GROUPS ---
        # Generated from: pd.get_dummies(..., prefix='age')
        Field(name="age_new", dtype=Bool),
        Field(name="age_mid_age", dtype=Bool),
        Field(name="age_legacy", dtype=Bool),
    ],
    online=True,
    source=historical_source,
    tags={"team": "maintenance_ops", "model_version": "v1.0"},
)